DEFINE TABLE i18n_interest TYPE NORMAL SCHEMAFULL PERMISSIONS none;

DEFINE FIELD id ON i18n_interest TYPE record<i18n_interest>;
DEFINE FIELD en ON i18n_interest TYPE string;
DEFINE FIELD de ON i18n_interest TYPE string;
DEFINE FIELD es ON i18n_interest TYPE string;
DEFINE FIELD fr ON i18n_interest TYPE string;
DEFINE FIELD it ON i18n_interest TYPE string;
DEFINE FIELD zh ON i18n_interest TYPE string;
DEFINE FIELD ja ON i18n_interest TYPE string;
DEFINE FIELD hu ON i18n_interest TYPE string;